server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5433/postgres
    username: postgres
    password: 1
  jpa:
    show-sql: true
  flyway:
    enabled: true
    user: postgres
    password: 1
    schemas: postgres
    url: jdbc:postgresql://127.0.0.1:5433/postgres
    locations: filesystem:db/migration