server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5433/test
    username: postgres
    password: 1
  jpa:
    show-sql: true
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: false
    user: postgres
    password: 1
    schemas: public
    url: jdbc:postgresql://127.0.0.1:5433/test
    locations: classpath:db.migration